version :  '3.7'
services : 
  NodeA : 
     build : 
      context : .
      dockerfile : Dockerfile
     image : custom_node
     restart : always
     container_name : vsomeip_node_a
     networks : 
      node_AB_net : 
        ipv4_address : 192.168.100.2

  NodeB : 
     build : 
      context : .
      dockerfile : Dockerfile
     image : custom_node
     restart : always
     container_name : vsomeip_node_b
     networks : 
      node_AB_net : 
        ipv4_address : 192.168.100.3
      node_BC_net : 
        ipv4_address : 192.168.200.3

  NodeC : 
     build : 
      context : .
      dockerfile : Dockerfile
     image : custom_node
     restart : always
     container_name : vsomeip_node_c
     networks : 
      node_BC_net : 
        ipv4_address : 192.168.200.2

networks : 
   node_AB_net : 
     name : vsomeip_node_AB_net
     ipam : 
      config : 
        - subnet : 192.168.100.0/24
   node_BC_net : 
     name : vsomeip_node_BC_net
     ipam : 
      config : 
        - subnet : 192.168.200.0/24

